+reviews:
+  auto_review:
+    enabled: true              # enable automatic review for new PRs
+  path_filters:                # skip generated or dependency files
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - "**/*.lock"